-d D:\Apps\Gowin\User\dht_lcd\impl\gwsynthesis\dht_lcd.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\Apps\Gowin\User\dht_lcd\src\dht_lcd.cst
-cfg D:\Apps\Gowin\User\dht_lcd\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
